version: "2"
services:
  dev:
    build: .
    image: keboola/google-drive-writer
    volumes:
      - .:/code
    tty: true
    stdin_open: true
    command: ./phpunit.sh
    environment:
      CLIENT_ID: $CLIENT_ID
      CLIENT_SECRET: $CLIENT_SECRET
      ACCESS_TOKEN: $ACCESS_TOKEN
      REFRESH_TOKEN: $REFRESH_TOKEN
      GOOGLE_DRIVE_FOLDER: $GOOGLE_DRIVE_FOLDER
      GOOGLE_DRIVE_TEAM_FOLDER: $GOOGLE_DRIVE_TEAM_FOLDER
      CODECLIMATE_REPO_TOKEN: $CODECLIMATE_REPO_TOKEN

  tests:
    build: .
    image: keboola/google-drive-writer
    tty: true
    stdin_open: true
    command: ./phpunit.sh
    environment:
      CLIENT_ID: $CLIENT_ID
      CLIENT_SECRET: $CLIENT_SECRET
      ACCESS_TOKEN: $ACCESS_TOKEN
      REFRESH_TOKEN: $REFRESH_TOKEN
      GOOGLE_DRIVE_FOLDER: $GOOGLE_DRIVE_FOLDER
      GOOGLE_DRIVE_TEAM_FOLDER: $GOOGLE_DRIVE_TEAM_FOLDER
      CODECLIMATE_REPO_TOKEN: $CODECLIMATE_REPO_TOKEN
