version: "2"
services:
  tests: &tests
    build: .
    image: keboola/google-drive-writer
    command: composer ci
    environment:
      CLIENT_ID: $CLIENT_ID
      CLIENT_SECRET: $CLIENT_SECRET
      ACCESS_TOKEN: $ACCESS_TOKEN
      REFRESH_TOKEN: $REFRESH_TOKEN
      GOOGLE_DRIVE_FOLDER: $GOOGLE_DRIVE_FOLDER
      GOOGLE_DRIVE_TEAM_FOLDER: $GOOGLE_DRIVE_TEAM_FOLDER

  dev:
    <<: *tests
    volumes:
      - .:/code
    command: bash
